# Generated by Django 5.0.3 on 2024-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.EmailField(max_length=50)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('Publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
